version: "3"
services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ome-db:/var/lib/mysql
    ports:
      - "3307:3306"
  cache:
    image: redis:6
    ports:
      - "6380:6379"
volumes:
  ome-db:
