version: "3"
services:
  web:
    build: ./php
    ports:
      - "8000:80"
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    volumes:
      - "../:/var/www/html"
    depends_on:
      - db
      - cache
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ome-db:/var/lib/mysql
      - ./data:/data
    ports:
      - "3307:3306"
  cache:
    image: redis:6
    ports:
      - "6380:6379"
volumes:
  ome-db:
